### ISSUE TITLE
Integration Not Available to Add

### ISSUE THREAD

**Issue by mcowger** [nonsleepr/ha-eufy-security#17]
I installed the custom repo in HACS, added the integration, restarted HA, and it looks right in HACS:

![Screen Shot 2020-10-20 at 2 57 11 PM](https://user-images.githubusercontent.com/1929548/96648680-8fd6e200-12e4-11eb-9cfe-ee8e11434c49.png)

However, when attempting to add the integration via the UI, its just not there:

![Screen Shot 2020-10-20 at 2 58 13 PM](https://user-images.githubusercontent.com/1929548/96648771-b85edc00-12e4-11eb-905d-effad34eec74.png)

It does seem to get loaded on startup:

```
config $ grep -i eufy home-assistant.log
2020-10-20 14:46:29 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for eufy_security which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant.
```

**Comment by mcowger** [comment]
After deleting and reinstalling, I'm able to configure the integrtion.

**Comment by aptonline** [comment]
I’m seeing the same issue although deleting and reinstalling doesn’t work for me.

**Comment by Julienh** [comment]
Hello, I have the same issues, someone found a solution please ? (I tried to reinstall)
