### ISSUE TITLE
Error Eufy Camera on camera.py:46

### ISSUE THREAD

**Issue by alesoft73** [nonsleepr/ha-eufy-security#26]
Hi,
i have this error on homeassitant version:2020.12.0

Logger: homeassistant.components.camera
Source: custom_components/eufy_security/camera.py:46
Integration: Telecamera (documentation, issues)
First occurred: 00:38:42 (1 occurrences)
Last logged: 00:38:42
Error while setting up eufy_security platform for camera

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

Many thanks for all!

**Comment by alesoft73** [comment]
I think the problem is 2fa login active into account...

**Comment by xekil** [comment]
Hello, I have the same problem and I am not using authentication 2fa :(

Home Assistant OS 5.8
Home Assistant 2020.12.0

**Comment by vdiogo** [comment]
Same problem here since yesterday. 
HASSIO 2020.12.6
Docker: 19.03.12

**Comment by rpitera** [comment]
Also being reported on the community forums

https://community.home-assistant.io/t/eufy-camera-integration/121758/372

**Comment by martoq** [comment]
One more for having the problem:

Operating System
Home Assistant OS 5.8

Supervisor
Version 2020.12.6

Eufy
0.3.0

**Comment by jwmcintosh** [comment]
Ditto, same issue here. 

**Operating System**
_Home Assistant OS 5.8_
**Version**
_2020.12.7_

Log Details (ERROR)
Logger: homeassistant.components.camera
Source: custom_components/eufy_security/camera.py:46
Integration: Camera (documentation, issues)
First occurred: 5:38:57 PM (4 occurrences)
Last logged: 7:24:19 PM

Error while setting up eufy_security platform for camera
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

**Comment by BillyFKidney** [comment]
Worked for me as well!

> I had the same issue here. See the link at the bottom for the (probable) fix.
> 
> **Operating System**
> _Home Assistant OS 5.8_
> **Version**
> _2020.12.7_
> 
> **Log Details (ERROR)**
> Logger: homeassistant.components.camera
> Source: custom_components/eufy_security/camera.py:46
> Integration: Camera (documentation, issues)
> First occurred: 5:38:57 PM (4 occurrences)
> Last logged: 7:24:19 PM
> 
> Error while setting up eufy_security platform for camera
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 199, in _async_setup_platform
> await asyncio.shield(task)
> File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
> [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
> File "/config/custom_components/eufy_security/camera.py", line 31, in 
> [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
> File "/config/custom_components/eufy_security/camera.py", line 46, in **init**
> self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
> TypeError: **init**() got an unexpected keyword argument 'loop'
> 
> The fix mentioned by @mikeskydev did work for me. Restart required, reloading integration will not due. https://community.home-assistant.io/t/eufy-camera-integration/121758/383
