### ISSUE TITLE
Future Home Assistant (2021.6) Requires version key in the manifest file

### ISSUE THREAD

**Issue by focher** [nonsleepr/ha-eufy-security#41]
The following WARNING is now issued in the log:

```[homeassistant.loader] No 'version' key in the manifest file for custom integration 'eufy_security'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'eufy_security'```

**Comment by mawiak** [comment]
Already fixed in Master-Branch.
Select Masterbranch in HACS install (last entry in drop down List)
