### ISSUE TITLE
Setting up integration from UI doesn't work

### ISSUE THREAD

**Issue by ping-localhost** [nonsleepr/ha-eufy-security#43]
When trying to add this integration via `config/integrations`, I get an `unknown error`: 

```json
{
  "type": "form",
  "flow_id": "9a46470b71424b64809f96e5d906a34c",
  "handler": "eufy_security",
  "step_id": "user",
  "data_schema": [
    {
      "type": "string",
      "name": "username",
      "required": true
    },
    {
      "type": "string",
      "name": "password",
      "required": true
    }
  ],
  "errors": {
    "base": "unknown_error"
  },
  "description_placeholders": null
}
```

Using version 0.3.0 and Home Assistant 2021.4.6

**Comment by rcwsr** [comment]
I was just getting the same response, but have you seen this post https://github.com/nonsleepr/ha-eufy-security/issues/37#issuecomment-799245094 ?

I tried creating another user, and I was able to log into the integration.

**Comment by ping-localhost** [comment]
> I was just getting the same response, but have you seen this post [#37 (comment)](https://github.com/nonsleepr/ha-eufy-security/issues/37#issuecomment-799245094) ?
> 
> I tried creating another user, and I was able to log into the integration.

I have a second account yes. Same issue :)

**Comment by ping-localhost** [comment]
Retried today and it just worked. No idea why, but it did, so closing this for now.
