### ISSUE TITLE
On fresh install on Home assistant core 5.3 cameras dont load

### ISSUE THREAD

**Issue by ryandelgrosso** [nonsleepr/ha-eufy-security#47]
The logs i get on load are: 

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 31, in <listcomp>
    [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
  File "/config/custom_components/eufy_security/camera.py", line 46, in __init__
    self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
TypeError: __init__() got an unexpected keyword argument 'loop'

**Comment by highlandtran** [comment]
do you have any update on this yet?

> The logs i get on load are:
> 
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
> await asyncio.shield(task)
> File "/config/custom_components/eufy_security/camera.py", line 31, in async_setup_entry
> [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
> File "/config/custom_components/eufy_security/camera.py", line 31, in
> [EufySecurityCam(hass, camera) for camera in api.cameras.values()], True
> File "/config/custom_components/eufy_security/camera.py", line 46, in **init**
> self._ffmpeg_image_frame = ImageFrame(self._ffmpeg.binary, loop=hass.loop)
> TypeError: **init**() got an unexpected keyword argument 'loop'

**Comment by alexdlm** [comment]
Not sure what the story with releases here is, but I found bumping the HACS install to Master resolved this issue as I could see the fix for this was in 5 months ago with dupe issue #26.

**Comment by yoshz** [comment]
I can confirm @alexdlm suggestion. Don't install version 0.3.0 which was released in 2019 but install the master branch.
Don't get why @nonsleepr doesn't tag a new release with all these new commits. A lot of issues are related to people using the old version.

**Comment by ryandelgrosso** [comment]
@yoshz that fixed it
