### ISSUE TITLE
Unable to process parameter "1148", value "0"

### ISSUE THREAD

**Issue by FuzzyMistborn** [nonsleepr/ha-eufy-security#5]
Not sure if this is HASS related or library related, but this is filling up my log:

`Unable to process parameter "1148", value "0"`

Last rebooted HASS ~3 days ago and have over 1500 entries with that line.  It's also been weird with the motion detection disabling.  Like...it's supposed to be disabled (I even check in the app) but the camera still activates on motion.

**Comment by laposheureux** [comment]
I have a pile of these as well, original kickstarter homebase:

```
Unable to process parameter "1138", value "19"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 3 times
Unable to process parameter "1240", value "1"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 6 times
Unable to process parameter "1045", value "0"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 9 times
Unable to process parameter "99904", value "0"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 9 times
Unable to process parameter "1149", value "0"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 6 times
Unable to process parameter "1131", value "1"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 9 times
Unable to process parameter "1241", value "1"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 6 times
Unable to process parameter "2111", value "2"
3:32 PM custom_components/eufy_security/camera.py (WARNING) - message first occurred at 3:27 PM and shows up 9 times
```

**Comment by FuzzyMistborn** [comment]
@nonsleepr any chance you could look at this?

**Comment by nonsleepr** [comment]
Yeah, I guess it was a bad idea to enable the logging for those options. Should turn it off.
For `1148` specifically it looks like it is `GET_CUSTOM1_ACTION`, but that doesn't tell me anything and would require digging deeper into the decompiled app.

**Comment by laposheureux** [comment]
I just switched to a V2 base station, will check and see if I'm still getting this or not tonight if I can.

**Comment by FuzzyMistborn** [comment]
I'm still puzzled why the motion detection is still firing after calling disabling the motion sensing.  There's got to be something else going on.

**Comment by nonsleepr** [comment]
Yes, the motion detection should be turned on/off using P2P protocol (I think I mentioned it in another issue). I'm not sure why they duplicate it in the REST API. We probably should remove that feature from the module for now since it's not working as expected.
